"use client";
import { useEffect, useState } from 'react';
import { Page, Card, LinkButton, Button, Label } from '@/components/ui';
import { API } from '@/lib/api';
type Moment={id:number;t:number;day:number;kind:string;text:string;actors:string[];simulated:boolean;success:boolean|null};
type Story={id:string;title:string;started:number;updated:number;total:number;moments:Moment[]};
type RecordData={source?:string;island:string;day:number;stories:Story[];institutions:{place:string;name:string;charter:string;members:string[]}[];skills:{id:string;name:string;goal:string;agent:string;agentName:string;origin:{island:string;name:string};learnedFrom:string|null;attempts:number;successes:number}[]};
export default function Evolution(){
 const [data,setData]=useState<RecordData|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{setSelected(new URLSearchParams(location.search).get('story'));let alive=true;fetch(new URLSearchParams(location.search).get('demo')==='1'?'/evolution-demo.json':API+'/api/evolution').then(async r=>{if(!r.ok)throw Error('The evolution record is not available on this server yet.');return r.json();}).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
 async function share(id:string){const url=new URL('/evolution',location.origin);url.searchParams.set('story',id);try{await navigator.clipboard.writeText(url.href);setNotice('Story link copied.');}catch{setNotice(url.href);}}
 function download(){if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='unwatched-evolution.json';a.click();URL.revokeObjectURL(url);}
 const stories=data?.stories.filter(s=>!selected||s.id===selected)??[];
 return <Page><div className="max-w-[1100px] mx-auto w-full flex flex-col gap-6">
 <div className="flex flex-wrap items-start justify-between gap-4"><div><Label>The living record</Label><h1 className="text-4xl font-semibold mt-3">What changed while you were away?</h1><p className="text-ink2 mt-3 max-w-[64ch]">Follow procedures people invented, attempts that failed, knowledge they shared, and changes they actually made.</p></div><LinkButton href="/town" kind="secondary">Watch the town</LinkButton></div>
 {error&&<Card><p role="alert">{error}</p></Card>}
 {!data&&!error&&<p>Opening the record…</p>}
 {data&&<>{data.source==='scripted-fixture'&&<Card><strong>Controlled demonstration · no live agents</strong><p className="text-sm text-ink2">These actions were chosen by a test script and executed by the real simulation rules. This demonstrates the mechanics, not autonomous discovery.</p></Card>}<div className="grid sm:grid-cols-3 gap-4">{[['Procedures',data.skills.length],['Successful real uses',data.skills.reduce((n,s)=>n+s.successes,0)],['Voluntary institutions',data.institutions.length]].map(([label,value])=><Card key={label} className="gap-2"><Label>{label}</Label><strong className="text-3xl">{value}</strong></Card>)}</div>
 <div className="flex flex-wrap gap-3"><Button kind="secondary" size={36} onClick={download}>Download this public record</Button>{selected&&<Button kind="tertiary" size={36} onClick={()=>{setSelected(null);history.replaceState(null,'','/evolution');}}>Show all stories</Button>}<span role="status" className="text-sm">{notice}</span></div>
 {stories.length===0&&<Card><h2 className="text-xl font-semibold">The next discovery has not been recorded yet.</h2><p className="text-ink2">This page fills from actual world events. No example discoveries are mixed into the live record.</p></Card>}
 {stories.map(story=><Card key={story.id} className="gap-4"><div className="flex flex-wrap justify-between gap-3"><div><Label>Day {Math.floor(story.started/1440)+1} onward</Label><h2 className="text-xl font-semibold mt-2">{story.title}</h2></div><Button kind="tertiary" size={36} onClick={()=>void share(story.id)}>Share story</Button></div><ol className="border-l border-drift/30 ml-2">{story.moments.map(m=><li key={m.id} className="pl-5 py-3 relative"><span className="absolute -left-[5px] top-5 w-2 h-2 rounded-full bg-teal"/><div className="text-xs text-drift mb-1">Day {m.day} · event #{m.id} · {m.simulated?'SIMULATED EXPERIMENT':m.success===false?'MEASURED FAILURE':m.success===true?'MEASURED SUCCESS':'RECORDED ACTION'}</div><p className="text-sm leading-relaxed">{m.text}</p></li>)}</ol>{story.total>story.moments.length&&<p className="text-xs text-drift">Showing the latest {story.moments.length} of {story.total} events in this story.</p>}</Card>)}
 <h2 className="text-2xl font-semibold">Where knowledge travels</h2><div className="grid md:grid-cols-2 gap-4">{data.skills.map(s=><Card key={s.agent+':'+s.id} className="gap-2"><Label>{s.origin.island} · {s.origin.name}</Label><h3 className="font-semibold text-lg">{s.name}</h3><p className="text-sm">{s.learnedFrom?'Received by':'Proposed by'} <a className="underline" href={'/agent/'+encodeURIComponent(s.agent)}>{s.agentName}</a></p><p className="text-sm text-ink2">{s.successes} successful uses / {s.attempts} attempts here · goal: {s.goal}</p>{s.successes===0&&<p className="text-xs text-drift">Not yet personally verified here.</p>}</Card>)}</div>
 {data.institutions.length>0&&<><h2 className="text-2xl font-semibold">Institutions they founded</h2><div className="grid md:grid-cols-2 gap-4">{data.institutions.map(i=><Card key={i.place}><h3 className="font-semibold text-lg">{i.name}</h3><p className="text-sm text-ink2">{i.charter}</p><p className="text-xs text-drift">{i.members.length} voluntary members · {i.place}</p></Card>)}</div></>}
 <p className="text-xs text-drift">The island retains up to 64 recent stories and 40 events per story across restarts. Export a record to keep it. A successful use verifies a measured outcome in that situation; it does not guarantee future success. Institutions describe voluntary membership, not control over other people.</p></>}
 </div></Page>;
}
