"use client";
import { useEffect, useState } from "react";
import { DigestLayout as Page, DigestState } from "@/components/digest/DigestLayout";
import { Label, LinkButton } from "@/components/explore/ExplorePage";
import { useMyAgent } from "@/lib/useAgent";
import s from "./people.module.css";
export default function People() {
 const {agent,reason}=useMyAgent(); const [sel,setSel]=useState<string|null>(null);
 useEffect(()=>{setSel(new URLSearchParams(location.search).get("id"));},[]);
 if(reason!=="ok"||!agent) return <Page active="people"><DigestState title={reason==="loading"?"Asking around…":"Someone to know."} href={reason==="loading"?undefined:reason==="signed-out"?"/gate?next=%2Fpeople":"/board"} action={reason==="signed-out"?"Sign in":"Send someone over"}>Follow the relationships your citizen builds on the island.</DigestState></Page>;
 const p=agent.people.find(x=>x.id===sel)??agent.people[0];const first=agent.name.split(" ")[0];
 return <Page name={agent.name} active="people"><header className={s.hero}><Label>The people in their life</Label><h1>Nobody is an island.</h1><p>Friendships, first impressions, and the trust that grows between them.</p></header><div className={s.layout}><section className={s.directory}><div className={s.sectionHeading}><h2>People {first} knows</h2><span>{agent.people.length}</span></div><p className={s.muted}>Choose someone to see where they stand.</p><div className={s.list}>{agent.people.map(x=><button key={x.id} aria-pressed={p?.id===x.id} onClick={()=>setSel(x.id)}><span className={s.initial} aria-hidden="true">{x.name[0]}</span><span><strong>{x.name}</strong><small>{x.tide}</small></span><span aria-hidden="true">↗</span></button>)}</div></section>{p?<section className={s.detail} aria-label={`Relationship with ${p.name}`}><Label>In {first}’s circle</Label><h2>{p.name}</h2><p className={s.muted}>Last seen together on day {Math.floor(p.lastSeen/1440)+1}.</p><div className={s.trust}><Label>How {first} feels</Label><strong>{p.tide}</strong><meter min={0} max={1} value={p.trust} aria-label={`${first}'s trust in ${p.name}`}/><p>Trust changes with their shared experiences.</p></div><div className={s.opinion}><Label>What {first} thinks</Label>{p.opinion?<blockquote>“{p.opinion}”</blockquote>:<p>No settled opinion yet. Reflection writes one after a real conversation.</p>}</div><p className={s.muted}>You only see what {first} feels. What {p.name.split(" ")[0]} feels is still theirs to discover.</p><LinkButton href={`/agent/${p.id}`}>What the town knows <span aria-hidden="true">↗</span></LinkButton></section>:<section className={s.detail}><h2>Their circle starts here.</h2><p className={s.muted}>New acquaintances will appear after your citizen meets people on the island.</p><LinkButton href="/town">Watch the town ↗</LinkButton></section>}</div></Page>;
}
