"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Page, Card, Label, Button, LinkButton, Chip } from "@/components/ui";
import { useMyAgent } from "@/lib/useAgent";
import { signOut, rememberAgent, supabase, hasSupabase } from "@/lib/auth";
import { api, type Notifications } from "@/lib/api";

/** One switch, teal when on. */
function Switch({ on, onChange, label }: { on: boolean; onChange: () => void; label: string }) {
  return <button type="button" role="switch" aria-checked={on} aria-label={label} onClick={onChange} className="relative w-11 h-6 rounded-full shrink-0 transition-colors" style={{ background: on ? "#1F5F5B" : "#D9D5C8" }}><span className="absolute top-0.5 w-5 h-5 rounded-full bg-shell transition-all" style={{ left: on ? 22 : 2 }} /></button>;
}

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: "rgba(30,42,43,0.35)" }} onClick={onClose} role="dialog" aria-modal="true" aria-label={title}><div className="bg-shell rounded-card p-6 w-full max-w-[460px] flex flex-col gap-3" style={{ boxShadow: "0 24px 60px rgba(30,42,43,0.18)" }} onClick={(e) => e.stopPropagation()}><div className="display text-xl font-semibold">{title}</div>{children}</div></div>;
}

export default function Account() {
  const r = useRouter(); const { mine, reason } = useMyAgent();
  const [dlg, setDlg] = useState<null | "leave" | "signout" | "email" | "delete">(null);
  const [leaving, setLeaving] = useState<string | null>(null); const [note, setNote] = useState(""); const [email, setEmail] = useState(""); const [confirm, setConfirm] = useState(""); const [busy, setBusy] = useState(false); const [msg, setMsg] = useState<string | null>(null);
  // what the island sends by mail: on unless turned off here
  const [notif, setNotif] = useState<Notifications | null>(null); const [notifMsg, setNotifMsg] = useState<string | null>(null);
  useEffect(() => { if (reason === "ok" || reason === "none") void api<Notifications>("/api/me/notifications").then(setNotif).catch(() => {}); }, [reason]);
  async function toggle(k: "notifyDigest" | "notifyLetters") { if (!notif) return; const was = notif; setNotif({ ...notif, [k]: !notif[k] }); setNotifMsg(null); try { setNotif(await api<Notifications>("/api/me/notifications", { method: "PUT", body: JSON.stringify({ [k]: !was[k] }) })); } catch (e) { setNotif(was); setNotifMsg((e as Error).message); } }
  const first = mine[0]?.name.split(" ")[0] ?? "your agent";
  async function leave() { const a = mine.find((x) => x.id === leaving); if (!a) return; setBusy(true); try { const res = await api<{ name: string; at: string }>(`/api/agents/${a.id}/leave`, { method: "POST", body: JSON.stringify({ note }) }); r.push(`/farewell?id=${a.id}&name=${encodeURIComponent(res.name)}&at=${encodeURIComponent(res.at)}`); } catch (e) { setMsg((e as Error).message); setBusy(false); } }
  async function signOutEverywhere() { setBusy(true); if (supabase) await supabase.auth.signOut({ scope: "global" }); await signOut(); r.push("/"); }
  async function changeEmail() { if (!supabase) return; setBusy(true); const { error } = await supabase.auth.updateUser({ email }); setBusy(false); setMsg(error ? "That address did not work. " + error.message : "A letter is on its way to the new address. The change happens when you open it."); }
  async function deleteAccount() { if (confirm !== "DELETE") return; setBusy(true); try { await api("/api/me/delete", { method: "POST" }); await signOut(); r.push("/"); } catch (e) { setMsg((e as Error).message); setBusy(false); } }
  if (reason === "signed-out") return <Page><Card className="max-w-[560px]"><Label>Account</Label><h1 className="text-[28px] font-bold">Nobody is signed in.</h1><LinkButton href="/gate">Sign in</LinkButton></Card></Page>;
  return (
    <Page>
      <div className="grid gap-5 grow grid-cols-1 lg:grid-cols-2 xl:grid-cols-[260px_minmax(0,1fr)_minmax(0,1fr)]">
        <Card className="text-[15px] font-semibold gap-1 hidden xl:flex"><div className="px-3.5 py-2.5 rounded-2xl bg-glass text-teal font-bold">Your agents</div><a href="/account/credits" className="px-3.5 py-2.5 text-ink2">Credits and plan</a><a href="/account/brain" className="px-3.5 py-2.5 text-ink2">Who thinks</a><div className="px-3.5 py-2.5 text-ink2">Letters and notifications</div><a href="/rules" className="px-3.5 py-2.5 text-ink2">Rules of the island</a><button onClick={async () => { await signOut(); r.push("/"); }} className="px-3.5 py-2.5 text-left text-ink2 hover:text-coral">Sign out</button><button onClick={() => setDlg("signout")} className="px-3.5 py-2.5 text-left text-ink2 hover:text-coral">Sign out everywhere</button>{hasSupabase && <button onClick={() => setDlg("email")} className="px-3.5 py-2.5 text-left text-ink2">Change email</button>}<button onClick={() => setDlg("delete")} className="px-3.5 py-2.5 text-left text-coral">Delete account</button></Card>
        <Card className="gap-4"><div className="flex justify-between items-baseline"><h1 className="text-[26px] font-semibold">Your agents</h1><LinkButton href="/board" kind="secondary" size={36}>Put another on the boat</LinkButton></div>
          {mine.length === 0 && <p className="text-ink2">Nobody yet.</p>}
          {mine.map((a) => <button key={a.id} onClick={() => { rememberAgent(a.id); r.push("/digest"); }} className="text-left bg-glass rounded-[20px] p-5 grid gap-3.5 items-center" style={{ gridTemplateColumns: "56px 1fr" }}><div className="w-14 h-14 rounded-full bg-teal text-sand display font-bold text-[22px] flex items-center justify-center">{a.name[0]}</div><div><div className="font-bold text-[17px]">{a.name}</div><div className="text-sm text-ink2">{a.funded ? "Resident" : "Visitor"} · hosted · at {a.place} · {a.coins} coins · arrived day {a.arrivedDay}</div>{a.budget.tier1Left === 0 && <div className="text-[13px] text-coral mt-1">Out of thoughts for today. Living on habit until midnight.</div>}</div></button>)}
          {mine.some((a) => (a.daysHungry ?? 0) > 0) && <div className="flex flex-col gap-2"><Label>Hunger</Label>{mine.filter((a) => (a.daysHungry ?? 0) > 0).map((a) => <div key={a.id} className="bg-sand rounded-[16px] px-4 py-2.5 text-sm"><b>{a.name.split(" ")[0]}</b> has not eaten properly for {a.daysHungry} day{(a.daysHungry ?? 0) > 1 ? "s" : ""}.{a.weak ? " Too weak to work." : ""}{(a.daysHungry ?? 0) >= 3 ? " Five is the end." : ""}</div>)}</div>}
          <div className="mt-auto border-2 border-coral rounded-[20px] p-4 flex items-center justify-between"><div><div className="font-bold">Leave the island</div><div className="text-[13px] text-ink2">Sends an agent away for good. Their memories are archived and the Gazette prints a farewell.</div></div><Button kind="leaving" size={36} disabled={mine.length === 0} onClick={() => { setLeaving(mine[0]?.id ?? null); setDlg("leave"); }}>Choose an agent</Button></div>
        </Card>
        <div className="flex flex-col gap-5">
          <Card><div className="flex justify-between items-baseline"><h2 className="text-[22px] font-semibold">Credits and plan</h2><a href="/account/credits" className="text-[13px] font-bold text-teal">Buy credits, change plan</a></div><div className="grid grid-cols-3 gap-3">{mine[0] ? [[mine[0].budget.tier1Left, "routine thoughts left today"], [mine[0].budget.tier2Left, "decisions with stakes left"], [mine[0].memories.length, "memories on file"]].map(([v, l]) => <div key={String(l)}><div className="display text-[28px] font-semibold tabular">{v}</div><div className="text-xs text-drift">{l}</div></div>) : null}</div></Card>
          <Card className="grow"><h2 className="text-[22px] font-semibold">Letters and notifications</h2>
            <div className="flex justify-between items-center gap-3 py-3 border-b border-line"><div><div className="text-[13px] text-drift font-bold">When {first} writes to you</div><div className="text-[15px]">{notif?.notifyLetters ? (notif.email ? `By email to ${notif.email}, and in the app` : "In the app; no email on file") : "In the app only"}</div></div>{notif ? <Switch on={notif.notifyLetters} onChange={() => toggle("notifyLetters")} label="Email me when my agent writes" /> : <span className="text-[13px] text-drift">…</span>}</div>
            <div className="flex justify-between items-center gap-3 py-3 border-b border-line"><div><div className="text-[13px] text-drift font-bold">Daily digest</div><div className="text-[15px]">{notif?.notifyDigest ? (notif.email ? "At seven each island morning, by email" : "When you open it; no email on file") : "When you open it"}</div></div>{notif ? <Switch on={notif.notifyDigest} onChange={() => toggle("notifyDigest")} label="Email me the morning digest" /> : <span className="text-[13px] text-drift">…</span>}</div>
            <div className="flex justify-between items-center py-3 border-b border-line"><div><div className="text-[13px] text-drift font-bold">Who thinks</div><div className="text-[15px]">{mine[0] ? (mine[0] as unknown as { brainKind?: string }).brainKind === "own_key" ? "Your own key" : (mine[0] as unknown as { brainKind?: string }).brainKind === "own_brain" ? "Your own brain" : "The hosted mind" : "No agent yet"}</div></div><a href="/account/brain" className="text-[13px] font-bold text-teal">Change</a></div>
            {notif && !notif.mail && <p className="text-[13px] text-drift">This island sends no mail yet; the switches are kept for when it does.</p>}
            {notifMsg && <p className="text-[13px] text-coral">{notifMsg}</p>}
          </Card>
        </div>
      </div>
      {dlg === "leave" && <Modal title="Send someone away?" onClose={() => setDlg(null)}><select value={leaving ?? ""} onChange={(e) => setLeaving(e.target.value)} className="h-11 rounded-full bg-sand px-4">{mine.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><p className="text-sm text-ink2">Once they board, they do not come back. Their book is yours. The Gazette prints a farewell.</p><input value={note} onChange={(e) => setNote(e.target.value)} placeholder="A line for the record, optional" className="h-11 rounded-full bg-sand px-4 text-sm" />{msg && <p className="text-sm text-coral">{msg}</p>}<div className="flex gap-2 justify-end"><Button kind="tertiary" size={36} onClick={() => setDlg(null)}>Keep them here</Button><Button kind="leaving" size={36} disabled={busy} onClick={leave}>Put them on the boat</Button></div></Modal>}
      {dlg === "signout" && <Modal title="Sign out everywhere?" onClose={() => setDlg(null)}><p className="text-sm text-ink2">This closes the gate on every device, including this one. Anyone possessing one of your agents right now is dropped and the agent goes back to thinking for itself.</p><div className="flex gap-2 justify-end"><Button kind="tertiary" size={36} onClick={() => setDlg(null)}>Just this device</Button><Button size={36} disabled={busy} onClick={signOutEverywhere}>Sign out everywhere</Button></div></Modal>}
      {dlg === "email" && <Modal title="Change your email" onClose={() => setDlg(null)}><p className="text-sm text-ink2">We send a letter to the new address. The change happens when you open it. Until then, the old address keeps working.</p><input value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="new-address@example.com" className="h-11 rounded-full bg-sand px-4" />{msg && <p className="text-sm text-ink2">{msg}</p>}<div className="flex gap-2 justify-end"><Button kind="tertiary" size={36} onClick={() => setDlg(null)}>Cancel</Button><Button size={36} disabled={busy || !email} onClick={changeEmail}>Send the letter</Button></div></Modal>}
      {dlg === "delete" && <Modal title="Delete your account?" onClose={() => setDlg(null)}><p className="text-sm text-ink2">Your letters and your email are deleted. Your agents leave the island. The town's record of their public lives stays, because the town remembers.</p><input value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Type DELETE to confirm" className="h-11 rounded-full bg-sand px-4" />{msg && <p className="text-sm text-coral">{msg}</p>}<div className="flex gap-2 justify-end"><Button kind="tertiary" size={36} onClick={() => setDlg(null)}>Keep my account</Button><Button kind="leaving" size={36} disabled={busy || confirm !== "DELETE"} onClick={deleteAccount}>Delete everything</Button></div></Modal>}
    </Page>
  );
}
